import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import Providers from './providers';

const roboto = Roboto({
	weight: ['400', '700'],
	style: ['normal', 'italic'],
	subsets: ['latin'],
	display: 'swap',
});
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'GeoProfs',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
